### ISSUE TITLE
Expainsion pack doesn't shows up in Garry's mod.

### ISSUE THREAD

**Issue by JustReg2Download** [VJ-HLR-Developers/Half-Life-2-Expansion#10]
It seems like something wrong happened.
![image](https://user-images.githubusercontent.com/72761693/129347031-1c328b0f-3a26-4acd-bd67-a6908c3de163.png)
![image](https://user-images.githubusercontent.com/72761693/129347055-32ae803c-99b6-4241-a12d-d05fe3a3b7cc.png)
![image](https://user-images.githubusercontent.com/72761693/129347090-ad402905-7ecc-4ad1-9b60-4631891a1efb.png)

P.S. I'd like to see all expansion NPCs in HL Resurgence on steam.

**Comment by JustReg2Download** [comment]
Worth to notice, I restarted gmod before making this thread.

**Comment by DrVrej** [comment]
We don't control how GMod loads addons, report it to GMod developers instead.
