### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by JustReg2Download** [VJ-HLR-Developers/Half-Life-2-Expansion#12]
1) Sleeping zombies do not react to any sound source from the player or NPCs. They also ignore any damage dealt to them and keep sleeping.

2) Overwatch Ion cannon has missing model parts.
![изображение](https://user-images.githubusercontent.com/72761693/168043795-943c00ab-ac31-4645-a062-5331e0fe7cba.png)

**Comment by JustReg2Download** [comment]
Note: I do not have any Half-Life-related games installed.
Installed: Half Life Resurgence , Half-Life-2-Expansion.

**Comment by Cpt-Hazama** [comment]
1.) They also don't do this in vanilla Half-Life 2, so yes, why would they react to sounds? As for damage, this works just fine for me
2.) If you haven't noticed yet, HLR2 is a WIP pack and some content requires Half-Life 2 and its Episodes installed and mounted
