### ISSUE TITLE
Missing parts of Hunter's behavior

### ISSUE THREAD

**Issue by jolopapina** [VJ-HLR-Developers/Half-Life-2-Expansion#13]
Hunter can't ram enemies, they don't have stun animation, but they should have. Please add.

**Comment by Cpt-Hazama** [comment]
Not sure if you're just trolling or something, but you do realize that this addon is no where near finished? Hence the reason its UNRELEASED? This was a very redundant post.... [🤦](https://emojipedia.org/person-facepalming/)

**Comment by jolopapina** [comment]
ok

**Comment by Cpt-Hazama** [comment]
1.) Because I didn't see it until now
2.) Its a genuine suggestion, and not a flat out useless post about unfinished AI

We work at our own pace on our own time, we are not slaves and have our own things in life to do, modding is 100% a free-time hobby. So, be patient and just wait

**Comment by jolopapina** [comment]
I know, I see VJ base development progress, you're working hard. This is just question/suggestion, it's not an order, I didn't say you have to fix it RIGHT NOW.
