### ISSUE TITLE
HL2 Ichthyosaur should be in this pack

### ISSUE THREAD

**Issue by Nin10doGMod** [VJ-HLR-Developers/Half-Life-2-Expansion#2]
Without Ichthyosaur, it wouldn't be a Half-Life 2 Expansion without everyone's favorite giant fish alien, since there is no Ichthyosaur in any of the Black Mesa SNPCs expansion pack.
[[VJ] Ichthyosaur SNPC.zip](https://github.com/VJ-HLR-Developers/Half-Life-2-Expansion/files/5159503/VJ.Ichthyosaur.SNPC.zip)

**Comment by Cpt-Hazama** [comment]
This is not an issue, closing useless report...
