### ISSUE TITLE
Antlion Guard is missing the alpha mask

### ISSUE THREAD

**Issue by BreavyTF2** [VJ-HLR-Developers/Half-Life-2-Expansion#3]
It's missing the alpha mask for normal map and appears to be stolen from my old Zombie Assassin addon, which has the same problem. An updated version for it is here https://steamcommunity.com/sharedfiles/filedetails/?id=1859014925. I also reccomend using the leak textures for the crab synth as they are just Higher quality the final.

**Comment by Cpt-Hazama** [comment]
Uh, we don't even know who you are lol. No Antlion Guard textures were stolen, I haven't even seen you or your addons before. Thanks anyway for the suggestion regarding the Crab Synth, we will look into it.
