### ISSUE TITLE
Combine Shoots Upper Then My Hitbox/Same With Enemy NPC

### ISSUE THREAD

**Issue by JustReg2Download** [VJ-HLR-Developers/Half-Life-2-Expansion#4]
For some reason some combines shoot upper then actual hitbox.
![image](https://user-images.githubusercontent.com/72761693/108591977-23442080-7374-11eb-8224-5e3a09ffd160.png)
I discovered that is because of one installed addon called  Sninctbur's Artificial Intelligence Improvements.
How could I let them work together without removing Sninctbur's Artificial Intelligence Improvements.
Sninctbur's Artificial Intelligence Improvements allows you to enchance their behavior when they hear a sound.
Issue showcase by this link.
https://youtu.be/TkEOie-Zz0s

I also tried to add INPC addon.
INPC just ingnored them and didn't change their AI at all.
Is it possible to make them compatible without INPC's creator (he left this game for good).

You can also see which features those addons implement.
Sninctbur: https://steamcommunity.com/sharedfiles/filedetails/?id=1396685893
INPC: https://steamcommunity.com/sharedfiles/filedetails/?id=632126111

**Comment by JustReg2Download** [comment]
P.S. In the video I showcased how  combine shoot with/without AI (just look at "AI enabled" button")

**Comment by JustReg2Download** [comment]
Wait, is it possible to defeat advisor?

**Comment by DrVrej** [comment]
Stop adding these mods to your Garry's Mod, they are horribly coded and conflict with SNPCs. Nothing we can do on our side.
