### ISSUE TITLE
Minor errors and glitches during my experience

### ISSUE THREAD

**Issue by JustReg2Download** [VJ-HLR-Developers/Half-Life-2-Expansion#6]
Models of overwatch soldiers have missing texture of their guns.
![image](https://user-images.githubusercontent.com/72761693/121097353-84e1ab00-c7fc-11eb-8d34-2398dbacf301.png)
Charge Bows arrows (projectiles) are stuck permanently when you shoot it anywhere.
![image](https://user-images.githubusercontent.com/72761693/121097532-ca9e7380-c7fc-11eb-9ea9-7e8dd8a68111.png)
Combine Sniper Rifle has missing audio effects of reloading and shooting.
This issue touches NPC Combine Sniper and it's weapon variant.

**Comment by JustReg2Download** [comment]
P.S. Worth to mention  that I've tried everything to fix this by myself.
I tried to reinstall gmod and cleaining up all cache files with other folders.
All of those steps still did not help me.

**Comment by Cpt-Hazama** [comment]
You probably don't own Half-Life 2 Episode 2

**Comment by DrVrej** [comment]
Thanks for posting this report, couple of points:
- The bow will be moved to this repository, in the future once it's finished it may move back to the base pack.
- I have checked the code for the Combine Sniper, and I do not see any missing sounds. I recommend posting the console error for me to see what exactly the error is because all the sounds for the sniper are independently placed in the HLR folder.

**Comment by JustReg2Download** [comment]
![image](https://user-images.githubusercontent.com/72761693/121355740-dc853100-c938-11eb-8afb-5ae69bbfa289.png)
Episode one and two were reinstalled.
Issue with Overwatched soldiers disappeared
![image](https://user-images.githubusercontent.com/72761693/121356273-5e755a00-c939-11eb-98ef-08f3ff5d225a.png)

Here what I saw in console during other bug tests:
Sniper Rifle during shooting and reloading: Failed to load sound "vj_hlr\hl2_weapon\combinesniper\sniper_fire.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_weapon\combinesniper\sniper_fire_dist.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_weapon\combinesniper\sniper_reload.wav", file probably missing from disk/repository

Shooting with Charge Bow: Giving Moonrise a weapon_vj_hlr2_chargebow
Failed to load sound "vj_hlr\hl2_weapon\chargebow\chargebow_1.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_weapon\chargebow\chargebow_3.wav", file probably missing from disk/repository. Arrows are still floating at the same place.
Audio issue with combine sniper still exist, however any errors in console were spotted.
P.S I can easily understand that all of issues contain missing audio files, however any method didn't help me.

**Comment by JustReg2Download** [comment]
P.S.S. Another bug with overwatch assasin.
Failed to load sound "vj_hlr\hl2_npc\ep1\npc\male01\cit_comehere.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_npc\ep1\npc\female01\cit_remarks23.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_npc\ep1\npc\female01\cit_alert_head06.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_npc\ep1\npc\male01\cit_alert_antlions08.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_npc\ep2\outland_12\reb1_prepare_battle_02.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_npc\ep2\outland_12\reb1_prepare_battle_01.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2b_npc\citizen\howdoyoulikeit01.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_npc\ep2\outland_02\griggs_fightlion_05.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_npc\ep1\npc\female01\cit_theyfoundus.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_npc\ep1\npc\male01\cit_buddykilled08.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_npc\ep1\npc\male01\cit_pain10.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_npc\ep2\male02\reb2_antlions12.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_npc\ep1\npc\male01\cit_theyfoundus.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_npc\ep1\npc\female01\cit_evac_casualty08.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_npc\ep2\male02\reb2_reload03.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_npc\ep1\npc\male01\cit_pain11.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_npc\ep1\npc\male01\cit_itsaraid.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_npc\ep1\npc\female01\cit_buddykilled09.wav", file probably missing from disk/repository
Failed to load sound "vj_hlr\hl2_npc\ep1\npc\female01\cit_evac_thanks04.wav", file probably missing from disk/repository

**Comment by JustReg2Download** [comment]
![image](https://user-images.githubusercontent.com/72761693/121527781-731e2480-ca03-11eb-8f2f-0bee747a5c88.png)

**Comment by JustReg2Download** [comment]
![image](https://user-images.githubusercontent.com/72761693/121542462-d5c9ed00-ca10-11eb-8bb2-7104383c1b4e.png)
Well, that's weird
I took files from this ZIP, for some reasons ZIP file is completely full without any missing files.
I am going to refresh addon folder.

**Comment by JustReg2Download** [comment]
Good news!
Sound issues disappeared without any consequences.
Issue with charge bow projectiles and NPC Relationship tool

**Comment by DrVrej** [comment]
- Completely revamped the charge bow and its bolt (https://github.com/DrVrej/VJ-Base/commit/1f37c92f510ccda63373776124bd348ac6f15bc6)
- Fixed NPC relationship tool not properly resetting player allies (https://github.com/VJ-HLR-Developers/Half-Life-Resurgence/commit/495e2eda71e16e29a8d0f6bc506dd803d7f1628f)

Enjoy!
